spring.application.name=teacher-information-system

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/managerDb}
spring.datasource.username=${DB_USERNAME:erwinya}
spring.datasource.password=${DB_PASSWORD:12345678}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

server.port=${SERVER_PORT:8081}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
